<Project>
  <PropertyGroup>
    <IsMuonroiTestProject Condition="'$(IsTestProject)' == 'true'">true</IsMuonroiTestProject>
    <IsMuonroiTestProject Condition="'$(IsMuonroiTestProject)' == '' and $([System.String]::Copy('$(MSBuildProjectName)').Contains('.Tests'))">true</IsMuonroiTestProject>
    <IsMuonroiTestProject Condition="'$(IsMuonroiTestProject)' == '' and $([System.String]::Copy('$(MSBuildProjectDirectory)').Contains('\\tests\\'))">true</IsMuonroiTestProject>
    <IsMuonroiTestProject Condition="'$(IsMuonroiTestProject)' == '' and $([System.String]::Copy('$(MSBuildProjectDirectory)').Contains('/tests/'))">true</IsMuonroiTestProject>
    <IsMuonroiTestProject Condition="'$(IsMuonroiTestProject)' == ''">false</IsMuonroiTestProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsMuonroiTestProject)' != 'true'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsMuonroiTestProject)' == 'true'">
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
